name: Update Channel Token and Create M3U

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update_channel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the script to update token and create m3u
      run: |
        python main.py
