name: Update M3U Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Hər gün 12:00-da yeniləmə (cron vaxtı)

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Get M3U8 links and update playlist
      run: |
        python - <<EOF
        import requests
        import re

        # Kanal URL-i və yeni token
        channel_url = "https://ecanlitv3.etvserver.com/xazartv.m3u8?tkn=w-2tS11TT7LOKrVVrqjN1A&tms=1740634801"
        new_token = "w-2tS11TT7LOKrVVrqjN1A"  # Yeni token

        # URL-i yeniləyirik
        new_url = re.sub(r'tkn=[^&]+', f'tkn={new_token}', channel_url)

        # M3U playlist faylına əlavə edirik
        M3U_FILE = "playlist.m3u"

        # M3U faylını yazırıq
        with open(M3U_FILE, "w", encoding="utf-8") as m3u:
            m3u.write("#EXTM3U\n")
            m3u.write("#EXTINF:-1, Xazartv\n")  # Kanal adı əlavə edilir
            m3u.write(f"{new_url}\n")  # Yenilənmiş URL

        print(f"✅ M3U playlist yeniləndi: {M3U_FILE}")
        EOF

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Auto-update M3U playlist"
        git push
