name: Update M3U Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Avtomatik olaraq gündəlik işləmək üçün

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests  # Skriptdə istifadə olunan kitabxanaları quraşdırır

    - name: Run update_playlist.py script
      run: |
        python3 ecanli/update_playlist.py  # Burada düzgün yola diqqət yetirin
