name: Auto Update Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip install -r requirements.txt

    - name: Run update_playlist.py script
      run: |
        python ecanli/update_playlist.py  # Faylın doğru yeri burada qeyd olunmalıdır
