name: Update M3U Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Hər gün 12:00-da yeniləmə (cron vaxtı)

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests selenium webdriver_manager

    - name: Get M3U8 links and update playlist
      run: |
        python - <<EOF
        import requests
        import re
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from webdriver_manager.chrome import ChromeDriverManager
        import time

        # Kanalların linklərini daxil edirik
        channels = [
            {"name": "Xazartv", "url": "https://ecanlitv3.etvserver.com/xazartv.m3u8?tkn=9ctUTj5jLCkNmWD_OxakCg&tms=1740634051", "slug": "xazartv"}
        ]

        M3U_FILE = "playlist.m3u"

        # Tokenin yenilənməsi üçün saytı açırıq
        def get_new_m3u8_link(channel_url):
            options = Options()
            options.add_argument("--headless")  # Başsız modda çalışsın

            driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
            driver.get(channel_url)
            
            time.sleep(5)

            try:
                token_link = driver.current_url
                return token_link
            except Exception as e:
                print(f"❌ Xəta: {e} | Kanal: {channel_url}")
                return None
            finally:
                driver.quit()

        with open(M3U_FILE, "w", encoding="utf-8") as m3u:
            m3u.write("#EXTM3U\n")
            
            for channel in channels:
                new_m3u8_link = get_new_m3u8_link(channel["url"])
                
                if new_m3u8_link:
                    m3u.write(f"#EXTINF:-1, {channel['name']}\n")
                    m3u.write(f"{new_m3u8_link}\n")
                else:
                    print(f"❌ Kanal linki yenilənmədi: {channel['name']}")

        print(f"✅ M3U playlist yeniləndi: {M3U_FILE}")
        EOF

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Auto-update M3U playlist"
        git push
